exports.targetHttp = "http://";

exports.allOrderStatus = [
  "active",
  "approve",
  "dispatch",
  "cancel",
  "complete",
  "tobereturned",
  "return",
];

exports.districts = [
  "achham",
  "arghakhanchi",
  "baglung",
  "baitadi",
  "bajhang",
  "bajura",
  "banke",
  "bara",
  "bardiya",
  "bhaktapur",
  "bhojpur",
  "chitwan",
  "dadeldhura",
  "dailekh",
  "dang deukhuri",
  "darchula",
  "dhading",
  "dhankuta",
  "dhanusa",
  "dholkha",
  "dolpa",
  "doti",
  "gorkha",
  "gulmi",
  "humla",
  "ilam",
  "jajarkot",
  "jhapa",
  "jumla",
  "kailali",
  "kalikot",
  "kanchanpur",
  "kapilvastu",
  "kaski",
  "kathmandu",
  "kavrepalanchok",
  "khotang",
  "lalitpur",
  "lamjung",
  "mahottari",
  "makwanpur",
  "manang",
  "morang",
  "mugu",
  "mustang",
  "myagdi",
  "nawalparasi",
  "nuwakot",
  "okhaldhunga",
  "palpa",
  "panchthar",
  "parbat",
  "parsa",
  "pyuthan",
  "ramechhap",
  "rasuwa",
  "rautahat",
  "rolpa",
  "rukum",
  "rupandehi",
  "salyan",
  "sankhuwasabha",
  "saptari",
  "sarlahi",
  "sindhuli",
  "sindhupalchok",
  "siraha",
  "solukhumbu",
  "sunsari",
  "surkhet",
  "syangja",
  "tanahu",
  "taplejung",
  "terhathum",
  "udayapur",
];

exports.mailAssets = {
  background: "../../mails/assets/images/illustration_empty_background.png",
  cart: "../../mails/assets/images/illustration_empty_cart.svg",
  content: "../../mails/assets/images/illustration_empty_content.svg",
  mail: "../../mails/assets/images/illustration_empty_mail.svg",
};
